### ISSUE TITLE
一些小建议吧

### ISSUE THREAD

**Issue by zsakvo** [wordway/extension#2]
- 悬浮图标大了一点，稍显突兀。这是和另外两个插件的对比情况
![image](https://user-images.githubusercontent.com/25399519/72452107-f7ad4900-37f7-11ea-9b36-b8b692a35259.png)

- 引擎希望加个 Google 翻译

**Comment by lijy91** [comment]
1. 悬浮图标尽量已经调小了一些
2. Google 翻译还在计划中
