### ISSUE TITLE
建议修改一下弹出被盖住了

### ISSUE THREAD

**Issue by treemoons** [wordway/extension#26]
- 部分被盖住了

![image](https://user-images.githubusercontent.com/46921153/112084478-d5fddd80-8bc3-11eb-90c2-f028fca7372e.png)

**Comment by treemoons** [comment]
是的，全英文的邮件。那怎么解决呢，只能复制到搜索框吗？

**Comment by lijy91** [comment]
是哪家的邮箱呢？

**Comment by treemoons** [comment]
189邮箱

**Comment by lijy91** [comment]
这好像暂时没有什么好办法，我看 Google 翻译插件也是类似的问题

**Comment by treemoons** [comment]
好吧，还是感谢你
&nbsp;

&nbsp;
     
 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月23日(星期二) 晚上8:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wordway/extension] 建议修改一下弹出被盖住了 (#26)





 
这好像暂时没有什么好办法，我看 Google 翻译插件也是类似的问题
 
&mdash;
